name: ory_kratos_client
version: 0.8.2-alpha.1
description: OpenAPI API client
homepage: https://www.ory.sh

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  dio: ^4.0.4
  built_value: ^8.1.4
  built_collection: ^5.1.1

dev_dependencies:
  built_value_generator: ^8.1.4
  build_runner: any
